### ISSUE TITLE
Calling Json not working anymore "Internal Server Error"

### ISSUE THREAD

**Issue by kingleroyg** [ricefield/hymnalAPI#2]
Hi All , I tried calling json using the following \
url : http://hymnalapi.herokuapp.com/hymn/1343
But all I get is "Internal Server Error" . 

Is the error with you guys or www.hymnal.net
If the server no longer exsist, could you tell me how too add it on mine ?
I know this is from 2013.

Thanks :) :+1:

**Comment by ricefield** [comment]
hi @kingleroyg sorry I haven't had time to look into this. You can easily deploy this project to Heroku on your own. Check out https://devcenter.heroku.com/articles/rack for a tutorial.

I'm not 100% sure what is wrong, but the code is definitely old and needs to be updated. I believe hymnal.net has changed their layout since I last touched this, so I wouldn't be surprised if the parsing is all broken.

Unfortunately I don't have the time to fix this right now, but feel free to submit a pull request if you want :)
